name: Build pismo
on:
  push:
    branches:
      - "main"

jobs:
  gorevive:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run env prepare revive (golint)
        run: go install github.com/mgechev/revive@latest
      - name: Run revive
        run: revive ./...
  go-unit-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run env go mod
        run: |
          go mod download
      - name: Run go unit tests
        run: go test -test.short -v ./...
  go-functional-test:
    needs: [gorevive, go-unit-test]

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run env go mod
        run: |
          go mod download
      - name: Run go functional test
        run: go test -v ./...
  build:
    needs: [gorevive, go-unit-test, go-functional-test]
    runs-on: ubuntu-20.04
    name: Checkout and build
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker image build
        run: |
          docker build . -t pismo
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: diegossantosws/pismo
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}