name: Build pismo
on:
  push:
    branches:
      - "main"

jobs:
  gorevive:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run env prepare revive (golint)
        run: go install github.com/mgechev/revive@latest
      - name: Run revive
        run: revive ./...
  go-unit-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run env go mod
        run: |
          go mod download
      - name: Run go unit tests
        run: go test -test.short -v ./...
  go-functional-test:
    needs: [gorevive, go-unit-test]

    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run env go mod
        run: |
          go mod download
      - name: Run go functional test
        run: go test -v ./...
  build:
    needs: [gorevive, go-unit-test, go-functional-test]
    runs-on: ubuntu-20.04
    name: Checkout and build
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker image build
        run: |
          docker build . -t pismo
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: diegosantosws/pismo:latest